spring:
  datasource:
    url: "jdbc:mysql://localhost:16120/cybersky"
    username: "cybersky"
    password: "Cyber.sky@305"
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:server.keystore
#    key-password: caonan
    key-alias: tomcat
    key-store-type: JKS
    key-store-password: caonan
http:
  port: 8080

logging:
  config: classpath:log4j2.xml

