spring:
  datasource:
    url: "jdbc:mysql://localhost/cybersky"
    username: "cybersky"
    password: "Cyber.sky@305"
  jdbc:
    template:
      query-timeout: 100
server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:server.keystore
#    key-password: caonan
    key-alias: tomcat
    key-store-type: JKS
    key-store-password: caonan
http:
  port: 8080

